version: '3.4'

services:
  db:
    container_name: bdd2-pgsql-parcial3
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: parcial3
