version: '3.4'

services:
  db:
    container_name: bdd2-mysql-parcial3
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'parcial3'
    ports:
      - 3307:3306
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
